### ISSUE TITLE
Prosegur Argentina

### ISSUE THREAD

**Issue by rodriguezwalter** [juanelegomezc/homebridge-prosegur#5]
Buenas tardes Juan, te quería preguntar si existe la posibilidad de usar este plugin con prosegur Argentina, estuve revisando y aparentemente utilizan la misma aplicación y plataforma de Colombia!

Desde ya te agradezco!
Saludos!

**Comment by juanelegomezc** [comment]
Hola Walter, claro que sí, voy a crear una versión nueva duplicando los valores que se usan para Colombia para Argentina y probemos si te funciona así.

**Comment by juanelegomezc** [comment]
Agregué una nueva version v1.0.4 con soporte para Argentina, usé la misma conf de Colombia, contame si te funciona bien o si tenés problemas para revisarlo.
